version: '3'
services:
  mongodb:
    container_name: mongo-puntify
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /data/db
  python:
    build: ./src
    volumes:
      - ./src/app:/code/app
    ports:
      - "80:80"
    links:
      - mongodb
    depends_on:
      - mongodb
