version: '3'
services:
  mongodb:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /data/db
  python:
    build: ./app
    volumes:
      - ./app:/usr/src/app
    ports:
      - "8000:8000"
    links:
      - mongodb
    depends_on:
      - mongodb
